default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: sm_dev 
  username: root
  password: 

test: &test
  <<: *default
  database: sm_test 
  username: root
  password: 

production:
  <<: *default
  database: sm_prod 
  username: root
  password: 

cucumber:
  <<: *test
